<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <Deterministic>true</Deterministic>
    <Features>strict</Features>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Authors>Hossam</Authors>
    <Product>AI_Orchestrator</Product>
  </PropertyGroup>

</Project>
