<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AIUsageMonitor.Application\AIUsageMonitor.Application.csproj" />
    <ProjectReference Include="..\AIUsageMonitor.Domain\AIUsageMonitor.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

</Project>
