// <auto-generated />
using System;
using AIUsageMonitor.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIUsageMonitor.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AIUsageMonitorDbContext))]
    partial class AIUsageMonitorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AIUsageMonitor.Domain.Alerts.AlertEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlertRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<double?>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AlertRuleId", "TriggeredAt");

                    b.ToTable("AlertEvents", (string)null);
                });

            modelBuilder.Entity("AIUsageMonitor.Domain.Alerts.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CriticalThreshold")
                        .HasColumnType("float");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("QuotaDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("WarningThreshold")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("QuotaDefinitionId");

                    b.ToTable("AlertRules", (string)null);
                });

            modelBuilder.Entity("AIUsageMonitor.Domain.Providers.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Providers", (string)null);
                });

            modelBuilder.Entity("AIUsageMonitor.Domain.Providers.ProviderConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CredentialReference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("LastAttempt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTimeOffset?>("LastSuccessfulSync")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("ProviderConnections", (string)null);
                });

            modelBuilder.Entity("AIUsageMonitor.Domain.Quotas.QuotaDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "ExternalKey")
                        .IsUnique();

                    b.ToTable("QuotaDefinitions", (string)null);
                });

            modelBuilder.Entity("AIUsageMonitor.Domain.Subscriptions.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("AutoRenew")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("BillingPeriodEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("BillingPeriodStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Cadence")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("CancelledDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTimeOffset?>("LastVerifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("OriginalStartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PlanName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RenewalDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("AIUsageMonitor.Domain.Sync.SyncEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("DataChanged")
                        .HasColumnType("bit");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "StartedAt");

                    b.ToTable("SyncEvents", (string)null);
                });

            modelBuilder.Entity("AIUsageMonitor.Domain.Usage.UsageSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuotaDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuotaDefinitionId");

                    b.HasIndex("ProviderId", "QuotaDefinitionId");

                    b.ToTable("UsageSnapshots", (string)null);
                });

            modelBuilder.Entity("AIUsageMonitor.Infrastructure.Persistence.SettingsEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("AIUsageMonitor.Domain.Alerts.AlertEvent", b =>
                {
                    b.HasOne("AIUsageMonitor.Domain.Alerts.AlertRule", null)
                        .WithMany()
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AIUsageMonitor.Domain.Alerts.AlertRule", b =>
                {
                    b.HasOne("AIUsageMonitor.Domain.Providers.Provider", null)
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AIUsageMonitor.Domain.Quotas.QuotaDefinition", null)
                        .WithMany()
                        .HasForeignKey("QuotaDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AIUsageMonitor.Domain.Providers.ProviderConnection", b =>
                {
                    b.HasOne("AIUsageMonitor.Domain.Providers.Provider", null)
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AIUsageMonitor.Domain.Quotas.QuotaDefinition", b =>
                {
                    b.HasOne("AIUsageMonitor.Domain.Providers.Provider", null)
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AIUsageMonitor.Domain.Subscriptions.Subscription", b =>
                {
                    b.HasOne("AIUsageMonitor.Domain.Providers.Provider", null)
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AIUsageMonitor.Domain.Sync.SyncEvent", b =>
                {
                    b.HasOne("AIUsageMonitor.Domain.Providers.Provider", null)
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AIUsageMonitor.Domain.Usage.UsageSnapshot", b =>
                {
                    b.HasOne("AIUsageMonitor.Domain.Providers.Provider", null)
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AIUsageMonitor.Domain.Quotas.QuotaDefinition", null)
                        .WithMany()
                        .HasForeignKey("QuotaDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AIUsageMonitor.Domain.Quotas.QuotaWindow", "Quota", b1 =>
                        {
                            b1.Property<Guid>("UsageSnapshotId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("CapturedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("CapturedAt");

                            b1.Property<string>("Confidence")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("Confidence");

                            b1.Property<string>("ExternalKey")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("ExternalKey");

                            b1.Property<double?>("LimitValue")
                                .HasColumnType("float")
                                .HasColumnName("LimitValue");

                            b1.Property<double?>("RemainingPercentage")
                                .HasColumnType("float")
                                .HasColumnName("RemainingPercentage");

                            b1.Property<double?>("RemainingValue")
                                .HasColumnType("float")
                                .HasColumnName("RemainingValue");

                            b1.Property<DateTimeOffset?>("ResetAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("ResetAt");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("Source");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("QuotaType");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("QuotaUnit");

                            b1.Property<double?>("UsedPercentage")
                                .HasColumnType("float")
                                .HasColumnName("UsedPercentage");

                            b1.Property<double?>("UsedValue")
                                .HasColumnType("float")
                                .HasColumnName("UsedValue");

                            b1.Property<DateTimeOffset?>("WindowStart")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("WindowStart");

                            b1.HasKey("UsageSnapshotId");

                            b1.ToTable("UsageSnapshots");

                            b1.WithOwner()
                                .HasForeignKey("UsageSnapshotId");
                        });

                    b.Navigation("Quota")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
